### ISSUE TITLE
一个可能的 git 实践

### ISSUE THREAD

**Issue by WokoLiu** [casdu/introduction#1]
https://github.com/komeiji-satori/Dress

也是最近流传很广的一个项目了，贴在这里，如果有人有兴趣，可以试一下实际操作

**Comment by randomwangran** [comment]
ca4cc28970f464d3f79effee578e51834f7b4ccd

**Comment by randomwangran** [comment]
@WokoLiu  作为自行车社团，当然是晒我们的爱车。

be923b25123a2a643ac4cb4fb73a973a1da02c85

**Comment by WokoLiu** [comment]
> @WokoLiu 作为自行车社团，当然是晒我们的爱车。
> 
> [be923b2](https://github.com/casdu/introduction/commit/be923b25123a2a643ac4cb4fb73a973a1da02c85)

说的对啊，我们可以类比这个项目，晒自己的车，待我晚上回去找找旧照片。

你说是再开一个项目好，还是就在这个项目里提照片？

**Comment by WokoLiu** [comment]
看到你已经提了

**Comment by randomwangran** [comment]
先在这个rep里？

估计不会很多人参与进来的。

**Comment by randomwangran** [comment]
我把 Dress 暂时从 Readme 移除。
主要是考虑，这是针对 CASDU 的 简介。CASDUer 的背景知识，我们是最了解的。所以我想借助任何想参与进来的 CASDUer 所有的疑惑，来编写属于 CASDUer 自己独特的知识 。
