### ISSUE TITLE
是不是可以上一篇介绍？

### ISSUE THREAD

**Issue by WokoLiu** [casdu/introduction#3]
看到第十五季会刊开始征稿，是不是可以搞一个简短的介绍？

[十五季会刊征稿令！！！](http://bbs.casdu.cn/forum.php?mod=viewthread&tid=11579&fromuid=39041)

**Comment by randomwangran** [comment]
a31cdbd982f84137b9861215d30f15537c3c8214

的确是这样，我分支上简单介绍一下，我们在干嘛。

3月17日。

**Comment by randomwangran** [comment]
@WokoLiu 

我觉得目前这些 rep 的状态还不足以吸引人。

1. route 最开是想读旺旺的帖子，更关注的是文字本身
2. training 是我平时自己的训练，因为我自己知道每周都要写一次这些数据，特别麻烦，所以想试试用程序语言来处理这些东西
3. huikan 的缘由和 route 很接近
4. tools 和 120 是我个人觉得可能有用的东西

但是，你也看到， 这些 rep 的状态还处在史前时代。

**Comment by WokoLiu** [comment]
huikan 我明天开始联系历届负责人，315之前至少整理出一期来看看样子

tools 和 120 ，我了解不多，这周末我问一下龙哥和医学的同学们，尝试整理一下 120，同样 315之前至少给个框架。tools不知道 @ywl0802 有没有兴趣搞一下，我争取在这周末找到一个或几个人来更新一下这个

route 和 training，暂时没有想法

**Comment by randomwangran** [comment]
@WokoLiu 这样会不会给他们压力太大了，下周就是315了。 

huikan 目前没有做太多东西，很大一部分原因是这会牵扯到很多作者，诸如文字版权之类的事情。会刊最开始发行的时候也只是在协会内部流传。可能会有作者不愿意把自己的东西放在网络上，或者别的什么原因。

关于这个组织帐号以及下面的这些仓库，我个人觉得不必要给大伙带来心理负担。我个人来讲，主要是这些东西都是我所感兴趣的，当然也期望有相同兴趣的朋友一起加入进来，毕竟“独乐乐不如众乐乐”。

**Comment by WokoLiu** [comment]
@randomwangran 我最近还算有空，不会把压力直接转到负责315的同学身上。之所以时间点定在 315 ，是想让你的介绍发出去之后，他们来看的时候，能至少有些东西展示

huikan 文字版权这个，我去找作者确认

> 关于这个组织帐号以及下面的这些仓库，我个人觉得不必要给大伙带来心理负担。我个人来讲，主要是这些东西都是我所感兴趣的，当然也期望有相同兴趣的朋友一起加入进来，毕竟“独乐乐不如众乐乐”。

赞同，放到 github 上的好处是，可以慢慢维护，长期维护。但昨天看到你说“还处在史前时代”，顿时觉得还是先多少出个样子，才好吸引别人的 pr。（我是说的有点急了

**Comment by randomwangran** [comment]
简单写了一下，你看怎么样？

> GitHub 是一个集分享与协作的平台。这么说， 是不是很熟悉？没错，我知道你想说：论坛。 与论坛不同，GitHub 就像二环东路上的怪坡。
> 
> 一遍一遍地爬怪坡或许是为了强健自己的躯体，或许是享受和挚友一起拼搏的时光，亦或是单单在乎和那一群人在路上的感觉。 车协不单单是一个骑自行车的社团，在这里你可以做得更多。 GitHub 就像怪坡一样，只不过这个怪坡，可以是任何你感兴趣的东西。散落在论坛里各种各样的骑行经验，或许把他们集中起来用更好看的格式排版出来；或许你自己就是公路车迷，年计划，月计划，不如分享出来或许你会找到同道之人；或许你觉得体训的方案可以是这个样子...
> 
> 论坛把车协人的精髓沉淀下来， GitHub 能我们走得更远。

**Comment by WokoLiu** [comment]
LGTM，顺便昨天我在跟负责会刊的同学解释 GitHub 的时候，说了这样一个观点：

> 虽然论坛上现在已经有很多“整理帖”，甚至很多版主新上任时也都会整理一遍，但是这些帖子都是很难被“不断更新”的。
> 
> 而在作者毕业后，再想在上面“稍微补充”一点内容，就会变得异常困难，而完全重写一遍的话，质量高低不说，还是做了很多重复工作。
> 
> 而 GitHub ，天生就是可以解决这个问题的。每一个简单的问题，都可以通过很多人的编辑，不断迭代，而臻于完美。

她总结说 “这个东西的意义在于多人编辑更新”，我觉得还是不错的

**Comment by randomwangran** [comment]
我加上了你的东西，然后又做了一些编辑和改动。

请参见最新的提交: 82e033602e98800a1cdb53d31452ff07b2566234

**Comment by WokoLiu** [comment]
@randomwangran 提交了去年会刊的目录: https://github.com/casdu/huikan/commit/978e505ef50fcf1c1127db38dea563b8e9ba2386

版权问题托付给上届会长了(也就是刚刚的提交里唯一一篇文章的作者)，貌似会刊这么多年也没考虑过这个问题，这次他们一起想一下

顺便，跟同学们沟通过程中发现，大部分人完全没听说过 git，更罔论 GitHub 了。对在校生来说，可能的确需要解释一下这个东西

**Comment by randomwangran** [comment]
@WokoLiu 

太棒了，如果版权问题能解决我们就可以一点点填砖加瓦了。 后续我会把我所知道的版权知识在这里和你讨论。比如 [GPL3](https://www.gnu.org/licenses/gpl-3.0.en.html) 还是 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)， 还是别的？

我觉得是本身 git 的属性决定了大多数不知道这种情况，但用 git 的人知道，它可以做超过编写软件的事情。GitHub 的诞生也只是11年前的事情，所以有机会的话，我也愿意向别人解释什么是 GitHub。

用 Git/GitHub 是有门槛的，我自己的亲身体验，14年注册之后，并没有太多的使用经历。只是后来，工作上的事情，GitHub 给我带来了太多好处: 同步，版本追踪，甚至是网盘... 到后来我发现 GitHub 上各种各样有意思的人，就更进一步加深了我和 GitHub 的联系。

**Comment by randomwangran** [comment]
@WokoLiu 

论坛上有蕾姐整理过的12年的会刊，是没有访问权限的。

我来整理那一期的。
